workflows:
  version: 2
  test_build:
      jobs:
        - test
        - dockerize:
            requires:
              - test
        - deploy:
            requires:
              - dockerize

jobs:
  test:
    docker:   
    - image: chandrarai/pythonapp:latest
    working_directory: ~/tmp
    steps:
      - add_ssh_keys:
           fingerprints:
             - "58:a2:74:6c:1d:17:85:32:61:46:9f:14:68:a6:8f:6d"
      - checkout

      - run: echo "This is just a test." > /tmp/testfile;
             
      - store_artifacts:
           path: /tmp/testfile
           destination: test_output
             
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to dockerhub
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/cir_chandra:$CIRCLE_SHA1 .
     
      - checkout

      # deploy the image to dockerhub
      - run: docker push $DOCKER_USER/cir_chandra:$CIRCLE_SHA1
   
  deploy:
    machine: true
    steps:
      - checkout

      - run: docker pull chandrarai/cir_chandra:$CIRCLE_SHA1    

      - run: ssh -i $login.pem ec2-user@ec2-18-222-158-72.us-east-2.compute.amazonaws.com "cd ~/devops/ && docker build -t app.py . && docker run --rm -p 8080:8080 app.py"
